name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v5
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          push: false
          tags: keebbuilder:temp

      - 
        name: Run Pytest
        uses: addnab/docker-run-action@v3
        with:
          image: keebbuilder:temp   
